### PR TITLE
Fixes/removes internal links

### PR DESCRIPTION
**Pull request by privatezero**
Fixes and removes anchors to permit building through the makefile

### CODE REVIEW

**Comment by retokromer** [comment]
Hi @privatezero, should I include these into https://github.com/privatezero/flac_markdown/pull/10? (Otherwise, I guess, we would hava an incompatibility.)

**Comment by privatezero** [comment]
Oh yes, thank you!

**Comment by retokromer** [comment]
Done, please cross check.

**Comment by privatezero** [comment]
incorporated into https://github.com/privatezero/flac_markdown/pull/10 so closing

**Pull request closed without merging**
