### PR TITLE
Fixed the representation of binary as suggested by issue #33

### PR DESCRIPTION
**Pull request by bumblebritches57**

### CODE REVIEW

**Comment by retokromer** [comment]
Why has this not been pushed?

**Comment by dericed** [comment]
@bumblebritches57 closed the branch. IMHO a commit in a pull request that was closed by the commit's author does not imply permission to merge. Potentially we should appeal to @bumblebritches57 to reconsider, else another contributor could redo the work.

**Comment by retokromer** [comment]
Hmm… what’s quicker? (I can «redo» the work.)

**Comment by bumblebritches57** [comment]
I deleted then restored the branch.

I got the notification that it was accepted and thought that meant it was merged in and still active.

AFAIK it's available again.

**Comment by bumblebritches57** [comment]
@dericed It was a mistake on my end, I did not mean to pull my changes from being submitted, I thought they were already accepted and merged.

Both branches are still available on my account, I'm just not sure how to relink them to the PRs I made a few days ago.

**Comment by dericed** [comment]
oh, welcome back, just click `Reopen and comment` at the bottom of https://github.com/privatezero/flac_markdown/pull/38

**Comment by dericed** [comment]
Given that this is reopened and received two reviews, I'm merging now while I'm able. :)

**Pull request merged**
