### PR TITLE
add contributing guide

### PR DESCRIPTION
**Pull request by retokromer**

### CODE REVIEW

**Comment by ablwr** [comment]
Shouldn't this direct people to the IETF mailing list, and maybe also the FLAC mailing list?

**Comment by retokromer** [comment]
Good point!

- [ ] [EBML](https://github.com/Matroska-Org/ebml-specification)
- [x] [Matroska]()

**Comment by privatezero** [comment]
I also see that it is now very easy to add a CODE_OF_CONDUCT file, would other's be in favor of adding one?

**Comment by dericed** [comment]
The IETF Code of Conduct would be appropriate. For other code of conducts you should probably consult to working group chairs or gather consensus.

**Comment by retokromer** [comment]
I personally have the Code of Conduct blues. The oldest I know has been released by… the mafia in Sicily! Yet I second the proposition of the IETF’s one.

**Comment by retokromer** [comment]
@dericed Do you mean [this one](https://www.internetsociety.org/get-involved/join-community/individuals/code-conduct)?

**Comment by privatezero** [comment]
Possibly [this one?](https://tools.ietf.org/html/rfc7154) That seems to be the most current one they have published.

When it comes to articulated codes, I suppose my feeling is, best to have one and not need it than vice versa!

**Comment by retokromer** [comment]
Yes, I guess this is what Dave was referring to!

I agree with you in theory, but the problem I have often noticed, in practice, is the difficulty to act when one feels the CoC has been broken.

**Pull request merged**
