### PR TITLE
add 0b to binary values

### PR DESCRIPTION
**Pull request by retokromer**
as discussed in https://github.com/privatezero/flac_markdown/pull/38#issuecomment-304284759

### CODE REVIEW

**Comment by dericed** [comment]
I suggest that in the convention section that the concept of `0b` as a prefix is defined, such as section 1.2 in https://tools.ietf.org/id/draft-bormann-apparea-bpack-00.txt.

**Comment by dericed** [comment]
I suggest closing in favor of https://github.com/privatezero/flac_markdown/pull/38

**Comment by retokromer** [comment]
OK

**Comment by bumblebritches57** [comment]
Sorry dude, I made a mistake in closing my branches, I got a message that said they were approved, and thought that meant merged as well, and that misconception has caused all kinds of havoc.

**Comment by retokromer** [comment]
No problem at all!

**Pull request closed without merging**
